import type { SecretPattern } from './types.js';

export const BUILT_IN_PATTERNS: SecretPattern[] = [
  {
    id: 'aws-access-key',
    name: 'AWS Access Key ID',
    pattern: /AKIA[0-9A-Z]{16}/g,
    severity: 'critical',
    category: 'api-keys',
    recommendation: 'Use AWS credentials file or IAM roles instead',
  },
  {
    id: 'aws-secret-key',
    name: 'AWS Secret Access Key',
    pattern: /aws_secret_access_key\s*=\s*[\w\/\+]{40}/gi,
    severity: 'critical',
    category: 'api-keys',
    recommendation: 'Use AWS credentials file or IAM roles instead',
  },
  {
    id: 'generic-api-key',
    name: 'Generic API Key',
    pattern: /api[_-]?key["\s:=]+([a-zA-Z0-9_\-]{20,})/gi,
    severity: 'high',
    category: 'api-keys',
    recommendation: 'Move to environment variable or secret management',
  },
  {
    id: 'stripe-key',
    name: 'Stripe API Key',
    pattern: /sk_(live|test)_[a-zA-Z0-9]{24,}/g,
    severity: 'critical',
    category: 'api-keys',
    recommendation: 'Revoke key immediately and use environment variables',
  },
  {
    id: 'rsa-private-key',
    name: 'RSA Private Key',
    pattern: /-----BEGIN RSA PRIVATE KEY-----/g,
    severity: 'critical',
    category: 'private-keys',
    recommendation: 'Remove private key and use secure key management',
  },
  {
    id: 'openssh-private-key',
    name: 'OpenSSH Private Key',
    pattern: /-----BEGIN OPENSSH PRIVATE KEY-----/g,
    severity: 'critical',
    category: 'private-keys',
    recommendation: 'Remove private key and use secure key management',
  },
  {
    id: 'github-token',
    name: 'GitHub Personal Access Token',
    pattern: /ghp_[a-zA-Z0-9]{36}/g,
    severity: 'critical',
    category: 'tokens',
    recommendation: 'Revoke token immediately and use GitHub secrets',
  },
  {
    id: 'slack-token',
    name: 'Slack Token',
    pattern: /xox[baprs]-[0-9a-zA-Z\-]{10,}/g,
    severity: 'high',
    category: 'tokens',
    recommendation: 'Revoke token and use environment variables',
  },
  {
    id: 'password-assignment',
    name: 'Password in Code',
    pattern: /password["\s:=]+["']([^"'\s]{8,})["']/gi,
    severity: 'high',
    category: 'passwords',
    recommendation: 'Use secure credential storage or environment variables',
  },
  {
    id: 'connection-string',
    name: 'Database Connection String',
    pattern: /(mongodb|postgres|mysql):\/\/[^:]+:[^@]+@/gi,
    severity: 'critical',
    category: 'credentials',
    recommendation: 'Use environment variables for connection strings',
  },
  {
    id: 'bearer-token',
    name: 'Bearer Token',
    pattern: /bearer\s+[a-zA-Z0-9_\-\.=]{20,}/gi,
    severity: 'high',
    category: 'tokens',
    recommendation: 'Use secure token management',
  },
];
